[theme]
primaryColor = "#FFE600"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#333333"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "viewer"

[logger]
level = "info"

[server]
headless = true
port = 8501
maxUploadSize = 200
enableXsrfProtection = true
